version: '3'
services:
  web:
    extends:
      file: docker-compose.base.yml
      service: web
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
