version: '3'
services:
  web:
    build: .
    image: echo_image
    ports:
      - "8000:8000"  # Expose port 8000
    volumes:
      - .:/app
    command: ["python", "/app/server/manage.py", "runserver", "0.0.0.0:8000" ]