version: '3'
services:
  web:
    build: .
    image: echo_image  # Set your desired image name
    env_file:
      - .env.dev  # Use the development environment variables
    ports:
      - "8000:8000"  # Expose port 8000
    volumes:
      - .:/app
    command: ["python", "/app/server/manage.py", "runserver"]
